---
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=1da1af59767d8c64ae960d5a0ac69089a0fa90e013aedb09e76843f104bec709
language: ruby
gemfile:
  - gemfiles/ams_0.10.0.rc4.gemfile
  - gemfiles/ams_0.10.2.gemfile
  - gemfiles/ams_0.10.8.gemfile
cache: bundler
rvm:
  - 2.3.4
before_install:
  - gem install -v 1.17.2 bundler --no-ri
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
