---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.8
before_install:
  - gem install bundler undercover
  - gem update --system
script:
  - bundle exec rake
  - git pull origin master:master
  - undercover --compare master
