---
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=1da1af59767d8c64ae960d5a0ac69089a0fa90e013aedb09e76843f104bec709
language: ruby
gemfile:
  - gemfiles/ams_0.10.0.rc4.gemfile
  - gemfiles/ams_0.10.0.gemfile
  - gemfiles/ams_0.10.2.gemfile
  - gemfiles/ams_0.10.3.gemfile
  - gemfiles/ams_0.10.8.gemfile
  - gemfiles/ams_0.10.10.gemfile
  - gemfiles/batch_loader_1.gemfile
  - gemfiles/batch_loader_2.gemfile
cache: bundler
rvm:
  - 2.5.3
  - 3.0.0
jobs:
  # Following AMS versions are locked to AR < 6 which isn't compatible with Ruby 3
  exclude:
  - rvm: 3.0.0
    gemfile: gemfiles/ams_0.10.2.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/ams_0.10.3.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/ams_0.10.8.gemfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
